In [ ]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.datasets import load_iris

# iris = load_iris(as_frame=True)
# df = iris.data


In [ ]:
df = sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df[['species']]
print(x)
print(y)

# x = df.iloc[:,:4]
# y = df['species']
# print(x)
# print(y)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=7)

In [ ]:
print(x_train)
print(y_train)

     sepal_length  sepal_width  petal_length  petal_width
17            5.1          3.5           1.4          0.3
102           7.1          3.0           5.9          2.1
124           6.7          3.3           5.7          2.1
76            6.8          2.8           4.8          1.4
132           6.4          2.8           5.6          2.2
..            ...          ...           ...          ...
142           5.8          2.7           5.1          1.9
92            5.8          2.6           4.0          1.2
103           6.3          2.9           5.6          1.8
67            5.8          2.7           4.1          1.0
25            5.0          3.0           1.6          0.2

[112 rows x 4 columns]
17         setosa
102     virginica
124     virginica
76     versicolor
132     virginica
          ...    
142     virginica
92     versicolor
103     virginica
67     versicolor
25         setosa
Name: species, Length: 112, dtype: object


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_test = sc.fit_transform(x_test)
x_train = sc.fit_transform(x_train)

print(x_test)
print(x_train)

[[ 0.07837971 -0.17595157  0.76150586  0.77656199]
 [-0.59853599 -0.17595157  0.39751564  0.35897677]
 [-1.14006855  0.97683457 -1.54376555 -1.31136411]
 [-0.32776971 -0.17595157  0.39751564  0.35897677]
 [-1.27545169 -1.32873771  0.39751564  0.63736691]
 [-1.81698425 -1.78985216 -1.54376555 -1.31136411]
 [ 1.43221111  0.05460566  0.64017578  0.35897677]
 [-0.32776971 -0.86762325  0.21552053  0.08058662]
 [-1.41083483  0.74627734 -1.36177043 -1.45055918]
 [ 0.75529541  0.28516289  0.39751564  0.35897677]
 [ 1.16144483 -0.17595157  0.70084082  0.63736691]
 [ 0.21376285  0.74627734  0.39751564  0.49817184]
 [-0.86930227  2.36017794 -1.42243547 -1.58975426]
 [ 1.83836053  1.2073918   1.36815623  1.7509275 ]
 [-0.86930227  0.74627734 -1.48310051 -1.45055918]
 [ 0.07837971  0.28516289  0.57951075  0.77656199]
 [ 1.16144483 -1.32873771  1.18616112  0.77656199]
 [ 0.75529541  0.05460566  1.00416601  0.77656199]
 [-1.00468541  1.66850626 -1.36177043 -1.45055918]
 [-1.27545169  1.2073918  -1.48

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_predict = nb.predict(x_test)
print(y_predict)

['virginica' 'versicolor' 'setosa' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'versicolor' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'setosa' 'virginica' 'setosa' 'virginica' 'virginica' 'virginica'
 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'versicolor' 'versicolor' 'virginica' 'virginica'
 'virginica' 'versicolor' 'setosa' 'virginica' 'versicolor' 'setosa'
 'setosa' 'setosa']


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, classification_report

acc = accuracy_score(y_test, y_predict)
print(acc)

pr = precision_score(y_test, y_predict, average='macro') # Using average because we have multiple classes
print(pr)

rc = recall_score(y_test, y_predict, average='macro')
print(rc)

cm = confusion_matrix(y_test, y_predict)
print(cm)

cr = classification_report(y_test, y_predict)
print(cr)

0.8947368421052632
0.9010989010989011
0.9010989010989011
[[11  0  0]
 [ 0 12  2]
 [ 0  2 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.86      0.86      0.86        14
   virginica       0.85      0.85      0.85        13

    accuracy                           0.89        38
   macro avg       0.90      0.90      0.90        38
weighted avg       0.89      0.89      0.89        38



In [ ]:
w = [[2.7,4.6,3.3,1.9]]
w = sc.fit_transform(w)

q = nb.predict(w)
print(q)

['versicolor']
